###########################################################################
###########################################################################
####  ██████╗  ██████╗     ██████╗ ███████╗███████╗███████╗████████╗   ####
#### ██╔════╝  ██╔══██╗    ██╔══██╗██╔════╝██╔════╝██╔════╝╚══██╔══╝   ####
#### ██║  ███╗ ██████╔╝    ██████╔╝█████╗  ███████╗█████╗     ██║      ####
#### ██║   ██║ ██╔═══╝     ██╔══██╗██╔══╝  ╚════██║██╔══╝     ██║      ####
####  ╚██████╔╝██║         ██║  ██║███████╗███████║███████╗   ██║      ####
####   ╚═════╝ ╚═╝         ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝   ╚═╝      ####
###########################################################################
###########################################################################

# Backups
backup:
  limit: 5

# Reset
reset:
  confirmation-timeout-seconds: 30

# World Specific
worlds:
  blacklist:
    - world_the_end
  ignore-global-region: true
