#  ██████╗  ██████╗     ██████╗ ███████╗███████╗███████╗████████╗
# ██╔════╝  ██╔══██╗    ██╔══██╗██╔════╝██╔════╝██╔════╝╚══██╔══╝
# ██║  ███╗ ██████╔╝    ██████╔╝█████╗  ███████╗█████╗     ██║
# ██║   ██║ ██╔═══╝     ██╔══██╗██╔══╝  ╚════██║██╔══╝     ██║
#  ╚██████╔╝██║         ██║  ██║███████╗███████║███████╗   ██║
#   ╚═════╝ ╚═╝         ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝   ╚═╝

# Config File for GP Reset plugin
backup:
  limit: 5

reset:
  confirmation-timeout-seconds: 30

worlds:
  blacklist:
    - world_the_end