name: GPReset
version: 0.1.4
main: org.plutonix.gPReset.GPReset
api-version: 1.21
author: Nathaniel Reed

softdepend:
  - GriefPrevention
  - WorldGuard

commands:
  gpreset:
    description: Reset world while preserving claims
    usage: /gpreset [command]
    permission: gpreset.admin

permissions:
  gpreset.admin:
    default: op