name: GPReset
version: 0.1.0
main: org.plutonix.gPReset.GPReset
api-version: 1.21
author: Nathaniel Reed

softdepend: [GriefPrevention]

commands:
  gpreset:
    description: Reset world while preserving claims
    usage: /gpreset <world> [confirm]
    permission: gpreset.admin

permissions:
  gpreset.admin:
    default: op